### ISSUE TITLE
Review Media Queries Level 4

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#16]
APA requests review of [Media Queries Level 4](https://www.w3.org/TR/mediaqueries-4/).

[APA tracking page for this review](https://www.w3.org/WAI/APA/wiki/Media_Queries_Level_4)

This spec is in wide review, so needs quick turnaround.

**Comment by patrickhlauke** [comment]
Possibly of interest: I've recently had a few PRs accepted on this https://github.com/w3c/csswg-drafts/pulls?utf8=%E2%9C%93&q=is%3Aclosed%20is%3Apr%20author%3Apatrickhlauke%20%5Bmediaqueries-4%5D, including some related to interaction media features and keyboard access (or rather, adding prose clarifying that authors should still consider keyboard access scenarios) https://github.com/w3c/csswg-drafts/pull/973

**Comment by IanPouncey** [comment]
This spec has been a final Working Draft since May 2017, so urgently need to find someone to review.

**Comment by IanPouncey** [comment]
@patrickhlauke has agreed to review.

**Comment by patrickhlauke** [comment]
is there any particular guidance / what to look for, or just a general "flag anything that feels like it could have an accessibility impact". and where do i mention whatever i find...here?

**Comment by michael-n-cooper** [comment]
For the most part people review based on their own expertise, so your general flag is right.

In the case of Media Queries, we're hoping for it to be a part of the solution for personalization, it's something that ARIA has been working on. I don't think I have pointers though. Just do your best, I'll also remind the ARIA group. I think though since we haven't matured our proposals, it won't lead to any specific comments on this version.

I suggest you put your initial thoughts either in this issue or on the task force mailing list. Ones that rise to the level of "APA comment" we would then delegate someone to file, though perhaps reviews done via the task force will just be filed more directly, by you as the reviewer for instance. I'll leave that part up to the facilitators to sort.

**Comment by patrickhlauke** [comment]
My best effort review of the spec (and I'll mention right away that I myself contributed to the spec, including the addition of some of the accessibility/keyboard related notes, so I'm biased):

Meta: SVG diagrams should be given a role="img" and appropriate description

Meta: the "asides" rendered as tooltips (see for instance the "all", "print", "screen", "speech" in https://www.w3.org/TR/mediaqueries-4/#media-types) cannot be triggered using the keyboard. 

https://www.w3.org/TR/mediaqueries-4/#media-types note that "tty", braille", "embossed", aural" etc are deprecated, due to no UA supporting them. However, "speech" is still maintained active. There is, to my knowledge, no evidence of UAs actually presenting themselves as "speech" type devices. Raised the issue here https://github.com/w3c/csswg-drafts/issues/1751

Interaction media features https://www.w3.org/TR/mediaqueries-4/#mf-interaction are based on the idea that devices/user agents have a "primary" pointing device. The non-normative notes suggest that user agents may have heuristics or user settings so that for keyboard users the queries for pointer:none (absence of a pointing device) should evaluate to true even if there are pointing devices (like a mouse or touchscreen) present. Note that, to my knowledge, no user agent currently does this/offers any kind of setting or heuristic.

The spec aknowledges that it does not include an equivalent media feature to detect the presence of a keyboard / keyboard-like interface, but includes a note suggesting that authors should "take into account the potential presence of non-pointing device inputs, regardless of which values are matched when querying these features".

Positive to note that https://www.w3.org/TR/mediaqueries-4/#pointer details how user agents should treat user zoom with regards to pointer accuracy - zoom does not influence the exposed value (e.g. a "coarse" pointer like a touchscreen does not suddenly become "fine" like a mouse when the user is zoomed in / the targets become visually bigger). 

This section also includes a "for accessibility reasons" section which hints at the possiblity that UAs would expose pointer accuracy as being coarse (or no primary pointer being present) despite a fine pointer being present (meta: this should probably be in a non-normative note). As above, tote that no user agent currently does this.

A similar "for accessibility reasons" section is present in https://www.w3.org/TR/mediaqueries-4/#hover, hinting that UAs may not expose the hover capabilities of the primary pointer if hovering is inconvenient for the user. Same note as before on lack of actual UA support for this.

https://www.w3.org/TR/mediaqueries-4/#any-input non-normative notes strongly mention the limitations of these media features in detecting keyboard users, and make recommendations to authors to still consider these users / not assume that these features (e.g. the fact that the media feature checks for pointers or hover capability) imply that all users will actually be using those potentially available input methods.

https://www.w3.org/TR/mediaqueries-4/#priv-sec covers the potential aspects of more accurately fingerprinting users. Worth noting that none of the media features would directly constitute a way to identify users with disabilities, with the exception of the "speech" media type https://www.w3.org/TR/mediaqueries-4/#valdef-media-speech. As I don't think there are any actual UAs that identify as "speech" type devices in the wild anyway, and due to the potential problem of "screenreader detection", I'd recommend officially deprecating this media type along with the already deprecated "tty", "braille", "aural" (again, see https://github.com/w3c/csswg-drafts/issues/1751)

**Comment by IanPouncey** [comment]
Further discussion should take place at the [filed issue](https://github.com/w3c/csswg-drafts/issues/1925).
